"""Generate a geometric test puppet and sine audio; no real people or model weights."""
import subprocess,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];sys.path.insert(0,str(ROOT))
from PIL import Image,ImageDraw
from studio.core import new,store,read,save,actor,action
root=Path(sys.argv[1]).resolve() if len(sys.argv)>1 else ROOT/'projects/geometric_demo';root.mkdir(parents=True,exist_ok=True);store(root,new());action(root,'add-speaker',{'name':'Demo Speaker','title':'Synthetic test puppet'})
p=read(root/'project.json');s=p['speakers'][0]
im=Image.new('RGB',(300,500),'white');d=ImageDraw.Draw(im);d.rounded_rectangle((80,180,220,360),20,fill='#aebacd',outline='#263248',width=3);d.ellipse((113,60,187,135),fill='#efc5a3',outline='#263248',width=3);d.rounded_rectangle((110,130,190,300),20,fill='#6554d6',outline='#263248',width=3);d.line((115,155,80,245),fill='#263248',width=9);d.line((185,155,220,245),fill='#263248',width=9);d.line((135,285,120,425),fill='#263248',width=17);d.line((165,285,190,425),fill='#263248',width=17);d.ellipse((95,415,135,438),fill='#263248');d.ellipse((180,415,220,438),fill='#263248');source=root/'input.png';im.save(source);action(root,'import-asset',{'speaker':s['id'],'path':str(source),'kind':'neutral'})
pose=im.copy();draw=ImageDraw.Draw(pose);draw.line((185,155,240,170),fill='#263248',width=9);source=root/'pose_input.png';pose.save(source);action(root,'import-asset',{'speaker':s['id'],'path':str(source),'kind':'pose','pose':'open_palm'})
audio=root/'input.wav';subprocess.run(['ffmpeg','-v','error','-y','-f','lavfi','-i','sine=frequency=220:sample_rate=48000','-t','4',str(audio)],check=True);action(root,'import-media',{'path':str(audio)});p=read(root/'project.json');save(root/'transcript/transcript.json',{'segments':[{'start':0,'end':2,'text':'This geometric puppet tests the stage.'},{'start':2,'end':4,'text':'No real person or speech model is included.'}],'words':[]});p['transcript']='transcript/transcript.json';p['settings']['backend']='still';p['clips']=[{'id':'first','title':'First test','start':0,'end':2,'speaker':s['id'],'intro':'A synthetic Studio test.','group':'demo','reviewed':True},{'id':'second','title':'Second test','start':2,'end':4,'speaker':s['id'],'intro':'','group':'demo','reviewed':True}];scene=read(ROOT/'scene_default.json');scene['intro']['duration']=1;scene['actors']=[actor(p['speakers'][0])];scene['actors'][0]['gestures'].update(mode='manual',cues=[{'start':.4,'end':1.6,'pose':'open_palm'}]);p['productions']=[{'id':'demo','name':'Demo production','clips':['first','second'],'intro_mode':'clip','output':'both','scene':scene}];store(root,p);print(root)
